### ISSUE TITLE
Scan.read() sys error with python 2.6 

### ISSUE THREAD

**Issue by effem-git** [jflesch/pyinsane#17]
In the file abstract.py at line 216, there is a "*sys*" wrong instruction for python 2.6.
<code>if sys.version_info.major < 3:</code>
In python 2.6 *sys.version_info* is a tuple and *version_info* hasn't attribute *major*.

The following command is good for all python version.
<code>sys.version_info[0]</code>

**Comment by jflesch** [comment]
Wow, I totally missed and forgot this ticket, sorry :(
Anyway, Python 2.6 isn't officially supported (I only have Python 2.7 available on my systems ; I should clarify than in the README). For such problems, you can send a pull request if you want.

I'm closing this ticket. Please comment if it's still a problem for you.
