### ISSUE TITLE
Abstract threaded scans lock task threading

### ISSUE THREAD

**Issue by rmackinnon** [jflesch/pyinsane#19]
The problem we're running into is, once a scan is initiated and the image is retrieved, there is no way to garbage collect the now dead session and end the thread safely.  It remains alive holding the device hostage.  Any attempt to .cancel() or \_\_del\_\_() the scan/session object results in python hanging/deadlocking.

An strace reveals that it's sitting on a FUTEX_WAIT_PRIVATE:
ioctl(0, SNDCTL_TMR_STOP or SNDRV_TIMER_IOCTL_GINFO or TCSETSW, {B38400 opost isig icanon echo ...}) = 0
rt_sigaction(SIGWINCH, {SIG_DFL, [], SA_RESTORER, 0x7fc3f45b30e0}, {0x7fc3ee3c5a50, [], SA_RESTORER|SA_RESTART, 0x7fc3f45b30e0}, 8) = 0
futex(0x248d0d0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>

It's 100% percent repeatable here:
```
#!/usr/bin/python2.7
import pyinsane.abstract_th as pyinsane
dev = pyinsane.get_devices()
tmp = dev[0].scan()
try:
    while true:
        tmp.scan.read()
except EOFError:
    pass
tmp.scan.cancel()
#or 
tmp.scan.__del__()
```
Maybe we're not quite understanding how to end and start a new thread/session?

**Comment by rmackinnon** [comment]
Work around seems to be to call sane_exit() followed by get_devices().  I just feel dirty having to do it that way...

**Comment by jflesch** [comment]
You shouldn't call tmp.scan.__del__() yourself. You should write "del tmp.scan" instead.
This is what is done in Paperwork and it works fine.

**Comment by jflesch** [comment]
API has been reworked. You shouldn't have to call 'del' anymore (also, there isn't even any "__del__()" anymore).
Please comment if you still have problems. Otherwise I'm closing this long forgotten ticket.

**Comment by rmackinnon** [comment]
Thanks man, I'll try this out and open a new issue if anything breaks. 

Cheers!
